
@startuml

/'
以下は別途部品として提供されるので不要とする
クレジットカードが既に利用されているかチェックする()
クレジットカードが利用可能なクレジットカードかチェックする()

'/

package domain {

個人情報 -up.> ユーザー
個人情報 -up.> 生年月日
個人情報 -up.> 住所
個人情報 -up.> 電話番号
個人情報 -up.> 昼間連絡先
個人情報 -left.> 希望メールアドレス
個人情報 -right.> クレジットカード情報
個人情報 <-up.会員
会員 ..> 接続コース
会員 ..> アカウント

入会可能条件 -left-> 生年月日
入会可能条件 -left-> クレジットカード情報
入会 -right> 個人情報
会員登録 -> 会員
会員登録 -> 接続コース
会員登録 -> アカウント

class 入会 {
入会を申し込む(個人情報)
}

class 入会可能条件 {
+boolean : 入会可能かどうか(生年月日, クレジットカード情報)
}

class 会員登録 {
+接続コース : 接続コースを設定する(接続コース)
+アカウント : メンバーIDとパスワード生成する()
+boolean : 会員登録する(会員)

}

class 個人情報 {

}

class ユーザー {
-氏名
-氏名かな
-性別
}

class 生年月日 {
-生年月日
+boolean : 20際以上かどうか()
}

class 住所 {
-郵便番号
-住所
}

class 電話番号 {
-電話番号
}

class 昼間連絡先 {
-昼間連絡先
}

class 希望メールアドレス {
-希望メールアドレス
}

class クレジットカード情報 {
-クレジットカード番号
-クレジットカード有効期限
-クレジットカードセキュリティコード

}

class 会員 {
}

class アカウント {
メンバーID
初期パスワード

}

class 接続コース {
ベーシック
}

}

@enduml