@startuml

package 会員 {
  class 会員情報 {
    - メンバーID
    - メールアドレス
    - 会員状態
  }

  enum 会員状態 {
    登録,
    退会
    + boolean すでに退会を申込している()
  }
}
package アカウント {
  class 会員アカウント {
    - メンバーID
    - パスワード
    }
}

  package 会員登録 {
    class 会員登録申請書 {
      - 氏名
      - 氏名かな
      - 性別
      - 生年月日
      - 郵便番号
      - 住所
      - 電話番号
      - 昼間連絡先
      - 希望するメールアドレス
      - クレジットカード番号
      - クレジットカード有効期限
      - クレジットカードセキュリティコード
    }

    class 会員登録 {
      - メンバーID
      - 会員アカウント
      - 登録申込日
      - 登録日
      - 個人情報
      - クレジットカード
      - コース情報
      - 希望するメールアドレス
    }
  }

  package 会員退会 {
    class 会員退会 {
      - メンバーID
      - 退会申込日
      - 退会日
      + boolean 退会できるか()
    }
  }

package コース情報 {
  class コース情報 {
    - メンバーID
    - コース
  }

  enum コース {
    ベーシック
  }

  コース情報 --> コース
}

package クレカ {
  class クレジットカード {
    - メンバーID
    - クレジットカード番号
    - クレジットカード有効期限
    - クレジットカードセキュリティコード
    + boolean 同一クレジットカード情報である()
    + boolean 有効期限が切れている()
    }
}

package 個人情報 {
  class 個人情報 {
    - メンバーID
    - 氏名
    - 氏名かな
    - 性別
    - 生年月日
    - 郵便番号
    - 住所
    - 電話番号
    - 昼間連絡先
    + boolean 二十歳未満()
  }
}

会員情報 --> 会員状態

会員登録 --> 個人情報
会員登録 --> クレジットカード
会員登録 --> コース情報

会員登録 --> 会員アカウント

個人情報  --> 会員情報
クレジットカード --> 会員情報
会員退会 "0..1" --> "1" 会員情報
会員アカウント --> 会員情報
会員登録 --> 会員情報


会員 -[hidden]--> コース

@enduml
